services:
  glpi_app:
    build:
      context: ./glpi
      dockerfile: Dockerfile
    container_name: glpi
    hostname: glpi
    volumes:
      - glpi_config:/etc/glpi
      - glpi_documents:/var/lib/glpi/files/data-documents
      - glpi_plugins:/usr/share/glpi/plugins
      - glpi_marketplace:/usr/share/glpi/marketplace
      - glpi_files_plugins:/var/lib/glpi/files/_plugins
      - glpi_backup:/backup
    networks:
      - glpi
    environment:
      - TIMEZONE=America/Sao_Paulo
      - VERSION_GLPI=10.0.17
      - DB_HOST=glpidb
      - DB_PORT=3306
      - DB_DATABASE=glpi
      - DB_USER=root
      - DB_PASSWORD=547t7qVX\rd3
    ports:
      - 2001:80
    links:
      - glpidb

  glpidb:
    image: mariadb:10
    container_name: glpibd
    networks:
      - glpi
    volumes:
      - glpi_db_log:/var/log/mysql
      - glpi_db_lib:/var/lib/mysql
      - glpi_db_backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=547t7qVX\rd3

networks:
  glpi:
    driver: bridge

volumes:
  glpi_config:
  glpi_documents:
  glpi_plugins:
  glpi_marketplace:
  glpi_files_plugins:
  glpi_backup:
  glpi_db_log:
  glpi_db_lib:
  glpi_db_backup:

